### ISSUE TITLE
SOCKS error when getting TCP service banners

### ISSUE THREAD

**Issue by livy111** [firefart/stunner#49]
When attempting a ConnectionBind request to a TCP service which replies with a banner the Connection is terminated with a SOCKS error: message size received mismatch extra data: openssh 5.2 abcd (banner).

Can be recreated with nmap banner scan
Proxychains nmap -sT -Pn -sV -p 22 1.2.3.4

See attached image
![ssh-fail1](https://github.com/firefart/stunner/assets/59734923/6ce86ffa-b88f-407a-bfd2-b84028d52dbd)

**Comment by firefart** [comment]
I think this should be fixed now, can you please try again with `go install github.com/firefart/stunner@latest`? (there is on new version released yet)

**Comment by livy111** [comment]
The issue is still present although it is a different error message. Surprisingly, it does return the banner when running NMAP. However, If I try to actually SSH to my server across the SOCKS it fails. 
![image](https://github.com/firefart/stunner/assets/59734923/cb5c4432-93c7-4c84-a57f-796281187616)

**Comment by firefart** [comment]
@livy111 strange I just tried to connect with proxychains via ssh and it works as expected. Can you connect to the target without proxychains? Does it work if you increase the timeout (in stunner)?
